spring:
  profiles:
    active: dev
---
server:
  port: 8001 
spring:
   profiles: dev
   application:
     name: microservicecloud-config-dept-client
   datasource:
       driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
       url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
       username: root
       password: 123456
       type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
   jpa:
       hibernate:
          ddl-auto: update
       show-sql: true          
eureka:
   client: #客户端注册进eureka服务列表内
      service-url:
         defaultZone: http://127.0.0.1:7001/eureka/
   instance:
      instance-id: dept-8001.com
      prefer-ip-address: true
---
---
server:
  port: 8002
spring:
   profiles: test
   application:
     name: microservicecloud-config-dept-client
   datasource:
       driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
       url: jdbc:mysql://localhost:3306/cloudDB02              # 数据库名称
       username: root
       password: 123456
       type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
   jpa:
       hibernate:
          ddl-auto: update
       show-sql: true         
eureka:
   client: #客户端注册进eureka服务列表内
      service-url:
         defaultZone: http://127.0.0.1:7001/eureka/
   instance:
      instance-id: dept-8002.com
      prefer-ip-address: true
info: 
   app.name: sxt-microservicecloud
   company.name: www.sxt.cn
   build.artifactId: $project.artifactId$
   build.version: $project.version$        
